name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install & Build
      run: |
        yarn install --frozen-lockfile
        yarn ci
